export const imgType = [
  {
    label: "Top image",
    imgName: "top-image",
    id: "topimage",
    imgObj: "topImage",
  },
  {
    label: "Bottom image",
    imgName: "bottom-image",
    id: "bottomimage",
    imgObj: "bottomImage",
  },
  {
    label: "",
    imgName: "",
    id: "",
    imgObj: "",
    hdd: "hidden",
  },
  {
    label: "Back image",
    imgName: "backpage-image",
    id: "backimage",
    imgObj: "backpageImage",
  },
  {
    label: "Panchang",
    imgName: "panchang-image",
    id: "panchang",
    imgObj: "panchangImage",
    hdd: "hidden",
  },
  {
    label: "",
    imgName: "",
    id: "",
    imgObj: "",
    hdd: "hidden",
  },
  {
    label: "Blank box 1",
    imgName: "blankbox-image-1",
    id: "blankbox1",
    imgObj: "blankBoxImage1",
  },
  {
    label: "Blank box 2",
    imgName: "blankbox-image-2",
    id: "blankbox2",
    imgObj: "blankBoxImage2",
  },
  {
    label: "Blank box 3",
    imgName: "blankbox-image-3",
    id: "blankbox3",
    imgObj: "blankBoxImage3",
  },
  {
    label: "Blank box 4",
    imgName: "blankbox-image-4",
    id: "blankbox4",
    imgObj: "blankBoxImage4",
  },
  {
    label: "Blank box 5",
    imgName: "blankbox-image-5",
    id: "blankbox5",
    imgObj: "blankBoxImage5",
  },
];
